trigger:
- azure*

pool: Default

variables:
  MAPPED_SUPER_SECRET_VARIABLE: $(SUPER_SECRET_VARIABLE)
  VAR_A: A
  VAR_B: B

jobs:
- job: generator
  steps:
  - bash: |
      LOG_FILE=${HOME}/test.log
      print_log () {
          echo "$@"
          echo "$@" >> "${LOG_FILE}"
      }

      rm -f ${LOG_FILE}
      docker run --rm -e MAPPED_SUPER_SECRET_VARIABLE staticfloat/binarybuilder.jl:master julia -e 'println("\"", ENV["MAPPED_SUPER_SECRET_VARIABLE"], "\"")'

    name: mtrx
    env:
      NICE_VARIABLE: ${MAPPED_SUPER_SECRET_VARIABLE}
      VAR_AB: "${VAR_A} and ${VAR_B}"
