# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure*

pool: Default

jobs:
- job: generator
  steps:
  - bash: |
      PROJECTS=$(git diff-tree --no-commit-id --name-only -r HEAD | grep -E ".+/.+" | cut -d/ -f1,2 | sort -u)
      EXCLUDE_PROJECTS=" LLVMBootstrap Rootfs "
      echo -n "##vso[task.setVariable variable=legs;isOutput=true]{"
      # TODO: deal with empty PROJECTS.  Related: filter excluded projects
      # before entering the for loop
      for PROJECT in ${PROJECTS}; do
          NAME=$(basename "${PROJECT}")
          if [[ "${EXCLUDE_PROJECTS}" == *" ${NAME} "* ]]; then
              continue
          fi
          echo -n "'${NAME}':{'myvar':'${PROJECT}'}, "
      done
      echo "}"
    name: mtrx
- job: runner
  dependsOn: generator
  strategy:
    matrix: $[ dependencies.generator.outputs['mtrx.legs'] ]
  steps:
  - script: |
      echo "Hostname is \"$(hostname)\""
      echo "I am in \"$(pwd)\""
      echo "Here there are \"$(ls)\""
      echo $(myvar)
