trigger:
- azure*

pool: Default

variables:
  MAPPED_SUPER_SECRET_VARIABLE: $(SUPER_SECRET_VARIABLE)
  VAR_A: A
  VAR_B: B

jobs:
- job: generator
  steps:
  - bash: |
      LOG_FILE=${HOME}/test.log
      print_log () {
          echo "$@"
          echo "$@" >> "${LOG_FILE}"
      }

      rm ${LOG_FILE}
      print_log "This is the value of my secret variable: \"$(SUPER_SECRET_VARIABLE)\""
      print_log "This is the value of my mapped variable: \"${MAPPED_SUPER_SECRET_VARIABLE}\""
      print_log "This is the value of my variable: \"${NICE_VARIABLE}\""
      print_log "This is the value of VAR_A: \"${VAR_A}\""
      print_log "This is the value of VAR_B: \"${VAR_B}\""
      print_log "This is the value of VAR_AB: \"${VAR_AB}\""
    name: mtrx
    env:
      NICE_VARIABLE: ${MAPPED_SUPER_SECRET_VARIABLE}
      VAR_AB: "$A and $B"
