trigger:
- azure*

pool: Default

variables:
  MAPPED_SUPER_SECRET_VARIABLE: $(SUPER_SECRET_VARIABLE)
  VAR_A: A
  VAR_B: B

jobs:
- job: generator
  steps:
  - bash: |
      LOG_FILE=${HOME}/test.log
      print_log () {
          echo "$@"
          echo "$@" >> "${LOG_FILE}"
      }

      rm -f ${LOG_FILE}
      # print_log "NICE_VARIABLE = \"$(NICE_VARIABLE)\""
      # docker run --rm -e NICE_VARIABLE staticfloat/binarybuilder.jl:master julia -e 'println("\"", ENV["NICE_VARIABLE"], "\"")'

      echo "##vso[task.logissue type=error]Something went very wrong."
      echo "##vso[task.logissue type=warning]Something went somewhat wrong."

    name: mtrx
    env:
      NICE_VARIABLE: ${MAPPED_SUPER_SECRET_VARIABLE}
      VAR_AB: "${VAR_A} and ${VAR_B}"
