# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git diff-tree --no-commit-id --name-only -r HEAD
    displayName: 'Show files modified in last commit'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
