trigger:
- azure*

pool: Default

variables:
  MAPPED_SUPER_SECRET_VARIABLE: $(SUPER_SECRET_VARIABLE)
  VAR_A: A
  VAR_B: B

jobs:
- job: generator
  steps:
  - bash: |
      git checkout master
      cd Z/ZeroMQ
      export TERM=xterm-16color
      julia --color=yes build_tarballs.jl --debug --verbose x86_64-linux-gnu

    name: mtrx
    env:
      NICE_VARIABLE: ${MAPPED_SUPER_SECRET_VARIABLE}
      VAR_AB: "${VAR_A} and ${VAR_B}"
