# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: generator
  steps:
  - bash: |
      FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
      echo -n "##vso[task.setVariable variable=legs;isOutput=true]{"
      for file in ${FILES}; do
          echo -n "'$(basename ${file})':{'myvar':'${file}'}, "
      done
      echo "}"
    name: mtrx
  # This expands to the matrix
  #   a:
  #     myvar: A
  #   b:
  #     myvar: B
- job: runner
  dependsOn: generator
  strategy:
    matrix: $[ dependencies.generator.outputs['mtrx.legs'] ]
  steps:
  - script: echo $(myvar) # echos A or B depending on which leg is running
